apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::098499087395:role/fluentbit-role
  name: fluentbit
  namespace: default
